#!/bin/bash
# https://stackoverflow.com/questions/6980090/how-to-read-from-a-file-or-stdin-in-bash
while read -r line
do
  #echo "$line"
  bash -c "$line"
  echo ""
  sleep 0.5
done < "${1:-/dev/stdin}"
