#!/bin/bash

curl -X POST "http://localhost:3000/api/tracking/adduser" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": 1, \"name\": \"Bob\", \"location\": [ { \"x\": 250, \"y\": 50, \"timestamp\": \"2019-08-26T16:26:00Z\" } ]}"

curl -X POST "http://localhost:3000/api/tracking/adduserlocation" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": 1, \"name\": \"Bob\", \"location\": { \"x\": 350, \"y\": 150, \"timestamp\": \"2019-08-26T16:27:00Z\" }}"

curl -X POST "http://localhost:3000/api/tracking/adduserlocation" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": 1, \"name\": \"Bob\", \"location\": { \"x\": 400, \"y\": 200, \"timestamp\": \"2019-08-26T16:28:00Z\" }}"

curl -X POST "http://localhost:3000/api/tracking/adduserlocation" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": 1, \"name\": \"Bob\", \"location\": { \"x\": 100, \"y\": 300, \"timestamp\": \"2019-08-26T16:29:00Z\" }}"

curl -X POST "http://localhost:3000/api/tracking/adduserlocation" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": 1, \"name\": \"Bob\", \"location\": { \"x\": 200, \"y\": 100, \"timestamp\": \"2019-08-26T16:30:00Z\" }}"

curl -X POST "http://localhost:3000/api/tracking/adduserlocation" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": 1, \"name\": \"Bob\", \"location\": { \"x\": 300, \"y\": 260, \"timestamp\": \"2019-08-26T16:31:00Z\" }}"

curl -X POST "http://localhost:3000/api/tracking/adduserlocation" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": 1, \"name\": \"Bob\", \"location\": { \"x\": 400, \"y\": 220, \"timestamp\": \"2019-08-26T16:32:00Z\" }}"

curl -X POST "http://localhost:3000/api/tracking/adduserlocation" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": 1, \"name\": \"Bob\", \"location\": { \"x\": 220, \"y\": 420, \"timestamp\": \"2019-08-26T16:33:00Z\" }}"

